name: gh pages build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          git fetch
          git checkout --track origin/gh-pages
          git merge --allow-unrelated-histories main
          npm install .
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "gh-pages generated"
          git push
